FROM maven:3-jdk-8 as builder
WORKDIR /spout
COPY . .
RUN mvn package -Dmaven.test.skip=true

FROM java:8
WORKDIR /vms
COPY --from=builder  /spout/target/spout-0.0.1-SNAPSHOT.jar ./spout.jar
CMD java -jar spout.jar
