FROM maven:3-jdk-8 as builder
WORKDIR /vms
COPY . .
RUN mvn package -P production -Dmaven.test.skip=true

FROM java:8
WORKDIR /vms
COPY --from=builder  /vms/target/videomanagementservice-0.0.1-SNAPSHOT.jar ./vms.jar
CMD java -jar vms.jar
