apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
    - port: 8080
  selector:
    app: api-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-external
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: api-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: api:v1
        volumeMounts:  
        - mountPath: /api/var
          name: storage
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: HOST_NAME_VMS
          value: vms-service-external
      volumes:
       - name: storage
         persistentVolumeClaim:
           claimName: volmeperclaim






































