apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumeper
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volmeperclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  
