FROM maven:3-jdk-8 as builder
WORKDIR /api
COPY . .
RUN mvn package -P production -Dmaven.test.skip=true

FROM java:8
WORKDIR /api
COPY --from=builder  /api/target/apigateway-0.0.1-SNAPSHOT.jar ./api.jar
CMD java -jar api.jar
