#-------------------------FUNZIONA TUTTO --------------------------
FROM wanggaopeng/ffmpeg-java:v1
WORKDIR /vps
ADD ./target/videoprocessingservice-0.0.1-SNAPSHOT.jar ./vps.jar
ADD script.sh ./script.sh
CMD  java -jar vps.jar





# -------------------------------------OK---------------------------------------------
#FROM java:8
#WORKDIR /vps
#RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
#RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
#RUN apt-get -o Acquire::Check-Valid-Until=false update
#RUN apt-get install -y ffmpeg
#ADD ./target/videoprocessingservice-0.0.1-SNAPSHOT.jar ./vps.jar
#ADD script.sh ./script.sh
#CMD  java -jar vps.jar
#FROM jrottenberg/ffmpeg:latest

#RUN apt install software-properties-common
#RUN apt-get -y update
#RUN add-apt-repository ppa:jonathonf/ffmpeg-4
#RUN apt-get install -y ffmpeg
#RUN apt-get -y update
#RUN ffmpeg -h


#RUN apt-get -y upgrade
#RUN ffmpeg -h
#RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
#RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
#RUN apt-get -o Acquire::Check-Valid-Until=false update
#ENTRYPOINT ["/bin/sh"]


# As suggested by a user, for some people this line works instead of the first one. Use whichever works for your case
# RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list